#
# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
services:
    mysql:
        container_name: "oai-mysql"
        image: mysql:8.0
        volumes:
            - ../common/oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ../common/mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net:
                ipv4_address: 192.168.71.131
    oai-amf:
        container_name: "oai-amf"
        image: oaisoftwarealliance/oai-amf:${AMF_TAG:-v2.1.10}
        environment:
            - TZ=Europe/Paris
            - OPERATOR_KEY=63bfa50ee6523365ff14c1f45f88737d
        volumes:
            - ${SYSTEM_CONFIG:-../common/sys_config.yaml}:/openair-amf/etc/config.yaml
        depends_on:
            - mysql
        networks:
            public_net:
                ipv4_address: 192.168.71.132
    oai-smf:
        container_name: "oai-smf"
        image: oaisoftwarealliance/oai-smf:${SMF_TAG:-v2.1.10}
        environment:
            - TZ=Europe/Paris
        volumes:
            - ${MINI_CONFIG:-../common/sys_config.yaml}:/openair-smf/etc/config.yaml
        depends_on:
            - oai-amf
        networks:
            public_net:
                ipv4_address: 192.168.71.133
    oai-upf:
        container_name: "oai-upf"
        image: oaisoftwarealliance/oai-upf:${UPF_TAG:-v2.1.10}
        environment:
            - TZ=Europe/Paris
        entrypoint: /bin/bash -c \
                    "echo '200 eth1_table' >> /etc/iproute2/rt_tables;"\
                    "ip route del default || true;"\
                    "ip route add default via 192.168.72.135 dev eth1 table eth1_table;"\
                    "ip rule add from 12.1.1.0/24 table eth1_table;"\
                    "/openair-upf/bin/oai_upf -c /openair-upf/etc/config.yaml -o"
        volumes:
            - ${MINI_CONFIG:-../common/sys_config.yaml}:/openair-upf/etc/config.yaml
        depends_on:
            - oai-smf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
            - NET_RAW
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.71.134
                interface_name: eth0
            traffic_net:
                ipv4_address: 192.168.72.134
                interface_name: eth1
    oai-ext-dn:
        privileged: true
        container_name: oai-ext-dn
        image: oaisoftwarealliance/trf-gen-cn5g:${TRFGEN_TAG:-latest}
        entrypoint: /bin/bash -c \
              "iptables-legacy -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.1.1.0/24 via 192.168.72.134 dev eth0;"\
              "iperf3 -s &"\
              "sleep infinity"
        depends_on:
            - oai-upf
        networks:
            traffic_net:
                ipv4_address: 192.168.72.135
        healthcheck:
            test: /bin/bash -c "ping -c 2 192.168.72.134"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-gnb:
        image: ${GNB_IMAGE:-oai-gnb-cuda}:${GNB_TAG:-latest}
        container_name: oai-gnb
        user: ${USER_ID:-0}:${GROUP_ID:-0}
        runtime: nvidia
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bring-up
            - SYS_NICE   # for thread affinity
            - IPC_LOCK   # to avoid page swapping
        environment:
            USE_B2XX: ${USE_B2XX:-}
            USE_ADDITIONAL_OPTIONS: ${GNB_RF_OPTIONS:-} --telnetsrv --reorder-thread-disable 1 --log_config.global_log_options level,nocolor,time ${GNB_EXTRA_OPTIONS:-} ${GNB_THREAD_POOL:-}
            ASAN_OPTIONS: detect_leaks=0
        depends_on:
            - oai-ext-dn
        networks:
            public_net:
                ipv4_address: 192.168.71.140
            e2_net:
                ipv4_address: 192.168.73.140
        ports:
            - 5556:5555
        devices:
            - /dev/bus/usb/:/dev/bus/usb/
        volumes:
            - /tmp/nvidia-mps:/tmp/nvidia-mps
            - /tmp/nvidia-log:/tmp/nvidia-log
            - ${GNB_CONFIG:-../common/gnb.sa.usrpb200.24prbs.conf}:/opt/oai-gnb/etc/gnb.conf
            - ../../plugins:/opt/oai-gnb/plugins # mount all plugins for weights, logs, data capture, etc.
        ipc: host
        healthcheck:
            test: /bin/bash -c "pgrep -f softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue:
        image: ${UE_IMAGE:-oai-nr-ue-cuda}:${UE_TAG:-latest}
        container_name: oai-nr-ue
        runtime: nvidia
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
            - SYS_NICE   # for thread affinity
            - IPC_LOCK   # to avoid page swapping
        environment:
            USE_B2XX: ${USE_B2XX:-}
            USE_ADDITIONAL_OPTIONS: ${UE_RF_OPTIONS:-} --log_config.global_log_options level,nocolor,time ${UE_EXTRA_OPTIONS:-}
        networks:
            public_net:
                ipv4_address: 192.168.71.150
        devices:
            - /dev/net/tun:/dev/net/tun
            - /dev/bus/usb/:/dev/bus/usb/
        volumes:
            - ${UE_CONFIG:-../common/nrue.uicc.conf}:/opt/oai-nr-ue/etc/nr-ue.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    nearRT-RIC:
        image: oai-flexric:${FLEXRIC_TAG:-latest}
        command: "stdbuf -o0 nearRT-RIC"
        container_name: nearRT-RIC
        networks:
            e2_net:
                ipv4_address: 192.168.73.154
        volumes:
            - ../common/flexric.conf:/usr/local/etc/flexric/flexric.conf
    monitor_xapp:
        image: oai-flexric:${FLEXRIC_TAG:-latest}
        container_name: monitor_xapp
        networks:
            e2_net:
                ipv4_address: 192.168.73.155
        ports:
            - "5555:5555"
        volumes:
            - ../common/flexric.conf:/usr/local/etc/flexric/flexric.conf
            - ${XAPP_SCRIPT:-../../plugins/ric_xapps/src/zmq_stats_server.py}:/xapp/xapp.py
        entrypoint: python3 /xapp/xapp.py
networks:
    public_net:
        driver: bridge
        name: oai-public-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "oai-public"
    traffic_net:
        driver: bridge
        name: oai-traffic-net
        ipam:
            config:
                - subnet: 192.168.72.128/26
        driver_opts:
            com.docker.network.bridge.name: "oai-traffic"
    e2_net:
        driver: bridge
        name: oai-e2-net
        ipam:
            config:
                - subnet: 192.168.73.0/24
        driver_opts:
            com.docker.network.bridge.name: "e2"
