services:
  mec-yolo:
    build:
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE:-nvcr.io/nvidia/pytorch:25.12-py3}
    image: mec-yolo:demo1-1
    container_name: mec-yolo
    gpus: all
    restart: unless-stopped
    networks:
      traffic_net:
        ipv4_address: 192.168.72.136
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=512m
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      MODEL_PATH: ${MODEL_PATH:-/models/yolo11n.pt}
      DEVICE: ${DEVICE:-0}
      DEFAULT_IMGSZ: ${DEFAULT_IMGSZ:-640}
      DEFAULT_CONF: ${DEFAULT_CONF:-0.25}
      DEFAULT_IOU: ${DEFAULT_IOU:-0.70}
      MAX_IMAGE_BYTES: ${MAX_IMAGE_BYTES:-8388608}
      MAX_CONCURRENT_INFERENCE: ${MAX_CONCURRENT_INFERENCE:-1}
    volumes:
      - ./models:/models:ro

  mec-route-init:
    image: alpine:3.20
    container_name: mec-route-init
    network_mode: "service:mec-yolo"
    depends_on:
      mec-yolo:
        condition: service_started
    cap_add:
      - NET_ADMIN
    command:
        - /bin/sh
        - -c
        - |
          until ip link show eth0 >/dev/null 2>&1; do sleep 1; done
          until ping -c 1 -W 1 192.168.72.134 >/dev/null 2>&1; do sleep 1; done
          ip route replace 12.1.1.0/24 via 192.168.72.134 dev eth0
          ip route
    restart: "no"

networks:
  traffic_net:
    external: true
    name: oai-traffic-net
