#
# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# this is a template. remove the .template extension to use
# contents of this file will be merged automatically with docker-compose.yaml
# uncomment the relevant lines

services:
  oai-gnb:
    volumes:
      ##### Profiling tools if needed
      # - /opt/nvidia/nsight-systems/:/opt/nvidia/nsight-systems
    ##### Run gdbserver for debugging
    #command: ["gdbserver",":7777","/opt/oai-gnb/bin/nr-softmodem","-O","/opt/oai-gnb/etc/gnb.conf"]
    # Profile with Nsight Systems
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    #entrypoint: /bin/bash
    #cap_add:
    # - SYS_ADMIN
